[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "aporthq-sdk-python"
version = "0.1.0"
description = "Python SDK for The Passport for AI Agents"
authors = [
    {name = "APort Team", email = "team@aport.io"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Security",
    "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
]
dependencies = [
    "aiohttp>=3.8.0",
    "typing-extensions>=4.0.0",
]
keywords = ["agent-passport", "ai", "authentication", "verification", "aport", "mcp", "middleware"]

[project.urls]
Homepage = "https://aport.io"
Documentation = "https://aport.io/docs"
Repository = "https://github.com/aporthq/aport-sdks-and-middlewares"
Issues = "https://github.com/aporthq/aport-sdks-and-middlewares/issues"

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "pytest-cov>=4.0.0",
    "black>=22.0.0",
    "isort>=5.0.0",
    "mypy>=1.0.0",
]

[tool.setuptools.packages.find]
where = ["src"]
include = ["aporthq_sdk_python*"]

[tool.black]
line-length = 88
target-version = ['py38']

[tool.isort]
profile = "black"
line_length = 88

[tool.mypy]
python_version = "3.8"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
